### ISSUE TITLE
Operations results should be list

### ISSUE THREAD

**Issue by SamMarkowitz** [orius123/slang-sublime#1]
The snippet for an operation:

``` yaml
operation name:
  # inputs:
  action:
  # outputs:
  results:
    SUCCESS: 1==1
```

has results as a map. It should be a list

``` yaml
results:
        - SUCCESS: 1==1
```
